package com.hbboys.app.domain;
// Generated 2017-7-17 18:43:57 by Hibernate Tools 3.5.0.Final

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int orderid;
	private Order order;
	private String text;

	public Comment() {
	}

	public Comment(Order order) {
		this.order = order;
	}

	public Comment(Order order, String text) {
		this.order = order;
		this.text = text;
	}

	public int getOrderid() {
		return this.orderid;
	}

	public void setOrderid(int orderid) {
		this.orderid = orderid;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
