package com.hbboys.app.domain;
// Generated 2017-7-17 18:43:57 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int orderid;
	private Good good;
	private User user;
	private Date time;
	private Comment comment;

	public Order() {
	}

	public Order(int orderid) {
		this.orderid = orderid;
	}

	public Order(int orderid, Good good, User user, Date time, Comment comment) {
		this.orderid = orderid;
		this.good = good;
		this.user = user;
		this.time = time;
		this.comment = comment;
	}

	public int getOrderid() {
		return this.orderid;
	}

	public void setOrderid(int orderid) {
		this.orderid = orderid;
	}

	public Good getGood() {
		return this.good;
	}

	public void setGood(Good good) {
		this.good = good;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Comment getComment() {
		return this.comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

}
