package com.hbboys.app.domain;
// Generated 2017-7-17 18:43:57 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer uid;
	private String username;
	private String password;
	private String tel;
	private String email;
	private Integer isseller;
	private Set<Good> goods = new HashSet<Good>(0);
	private Set<Order> orders = new HashSet<Order>(0);

	public User() {
	}

	public User(String username, String password, String tel, String email, Integer isseller, Set<Good> goods, Set<Order> orders) {
		this.username = username;
		this.password = password;
		this.tel = tel;
		this.email = email;
		this.isseller = isseller;
		this.goods = goods;
		this.orders = orders;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getIsseller() {
		return this.isseller;
	}

	public void setIsseller(Integer isseller) {
		this.isseller = isseller;
	}

	public Set<Good> getGoods() {
		return this.goods;
	}

	public void setGoods(Set<Good> goods) {
		this.goods = goods;
	}

	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
